// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mcfapi.Data;

#nullable disable

namespace mcfapi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240916003644_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mcfapi.Models.ms_storage_location", b =>
                {
                    b.Property<string>("location_id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("location_id");

                    b.ToTable("ms_storage_location");
                });

            modelBuilder.Entity("mcfapi.Models.ms_user", b =>
                {
                    b.Property<long>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("user_id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("user_id");

                    b.ToTable("ms_user");
                });

            modelBuilder.Entity("mcfapi.Models.tr_bpkb", b =>
                {
                    b.Property<string>("agreement_number")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("bpkb_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bpkb_date_in")
                        .HasColumnType("datetime2");

                    b.Property<string>("bpkb_no")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("branch_id")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("faktur_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("faktur_no")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("last_updated_by")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("last_updated_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("location_id")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("police_no")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("agreement_number");

                    b.HasIndex("location_id");

                    b.ToTable("tr_bpkb");
                });

            modelBuilder.Entity("mcfapi.Models.tr_bpkb", b =>
                {
                    b.HasOne("mcfapi.Models.ms_storage_location", "ms_storage_location")
                        .WithMany("tr_bpkbs")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ms_storage_location");
                });

            modelBuilder.Entity("mcfapi.Models.ms_storage_location", b =>
                {
                    b.Navigation("tr_bpkbs");
                });
#pragma warning restore 612, 618
        }
    }
}
